services:
  docmost:
    build:
      context: .
    depends_on:
      - redis
    environment:
      APP_URL: ${APP_URL}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./docmost_data:/app/data/storage

  redis:
    image: redis:8
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "noeviction"]
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
