services:
  traefik-certs-dumper:
    image: ldez/traefik-certs-dumper:v2.10.0
    entrypoint: sh -c '
      while ! [ -e /data/acme.json ]
      || ! [ `jq ".[] | .Certificates | length" /data/acme.json | jq -s "add" ` != 0 ]; do
      sleep 1
      ; done
      && traefik-certs-dumper file --version v3 --watch --clean
      --domain-subdir --source /data/acme.json --dest /data/certs'
    volumes:
      - /etc/dokploy/traefik/dynamic/acme.json:/data/acme.json
      - dokploy-certs:/data/certs
    network_mode: "none"

volumes:
  dokploy-certs:
    driver: local
    name: dokploy-certs