services:
  zitadel:
    image: "ghcr.io/zitadel/zitadel:v4.2.2"
    command: 'start-from-init --masterkeyFromEnv'
    environment:
      ZITADEL_MASTERKEY: "${ZITADEL_MASTERKEY}"
      ZITADEL_EXTERNALDOMAIN: "${ZITADEL_EXTERNALDOMAIN}"

      # Database configuration (external DB)
      ZITADEL_DATABASE_POSTGRES_HOST: "${ZITADEL_DATABASE_POSTGRES_HOST}"
      ZITADEL_DATABASE_POSTGRES_PORT: "${ZITADEL_DATABASE_POSTGRES_PORT}"
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: "${ZITADEL_DATABASE_POSTGRES_USER_USERNAME}"
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: "${ZITADEL_DATABASE_POSTGRES_USER_PASSWORD}"
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: "${ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME}"
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: "${ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD}"

      # FirstInstance / initial org & human admin (only variables present in your .env)
      ZITADEL_FIRSTINSTANCE_ORG_NAME: "${ZITADEL_FIRSTINSTANCE_ORG_NAME}"
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: "${ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME}"
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_FIRSTNAME: "${ZITADEL_FIRSTINSTANCE_ORG_HUMAN_FIRSTNAME}"
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_LASTNAME: "${ZITADEL_FIRSTINSTANCE_ORG_HUMAN_LASTNAME}"
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_ADDRESS: "${ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_ADDRESS}"
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_VERIFIED: "${ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_VERIFIED}"
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PREFERREDLANGUAGE: "${ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PREFERREDLANGUAGE}"
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: "${ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD}"
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: "${ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED}"

      # login client PAT output
      ZITADEL_FIRSTINSTANCE_LOGINCLIENTPATPATH: /app-data/login-client.pat
      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_USERNAME: login-client
      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_NAME: Automatically Initialized IAM Login Client
      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_PAT_EXPIRATIONDATE: "2029-01-01T00:00:00Z"

      # runtime / start options
      ZITADEL_EXTERNALPORT: "${ZITADEL_EXTERNALPORT}"
      ZITADEL_EXTERNALSECURE: "${ZITADEL_EXTERNALSECURE}"
      ZITADEL_TLS_ENABLED: "${ZITADEL_TLS_ENABLED}"

    healthcheck:
      test: ["CMD", "/app/zitadel", "ready"]
      interval: "10s"
      timeout: "5s"
      retries: 5
      start_period: "10s"
    volumes:
      - "./app-data:/app-data:rw"
    networks:
      - default
      - dokploy-network

  login:
    restart: "unless-stopped"
    image: "ghcr.io/zitadel/zitadel-login:latest"
    environment:
      - ZITADEL_API_URL=http://zitadel:8080
      - NEXT_PUBLIC_BASE_PATH=/ui/v2/login
      - ZITADEL_SERVICE_USER_TOKEN_FILE=/app-data/login-client.pat
      - CUSTOM_REQUEST_HEADERS=Host:${ZITADEL_EXTERNALDOMAIN}
    volumes:
      - "./app-data:/app-data:ro"
    depends_on:
      zitadel:
        condition: "service_healthy"
    networks:
      - default
