services:
  headscale:
    image: headscale/headscale:stable
    restart: unless-stopped
    volumes:
      - ../../files/etc/headscale/config.yaml:/etc/headscale/config.yaml # Dokploy mount
      - ./lib:/var/lib/headscale
      - ./run:/var/run/headscale
    command: serve
